### ISSUE TITLE
Two repeated requests with the same Idempotency-Key header will be re-executed.

### ISSUE THREAD

**Issue by sunnyyssh** [VarthanV/gin-idempotency#4]
This middleware doesn't prevent us from re-executing. Only no execution when no header
It is not idempotency, unfortunately

**Comment by VarthanV** [comment]
@sunnyyssh, thank you for raising the issue. I understand the problem you're highlighting. When I initially designed this middleware, the focus was on checking the presence of the idempotency key and delegating the comparison logic to the handler. My proposed solution is to introduce a `CanAllow` field when initializing the middleware, with the following signature:

```go
func(val ...interface{}) bool
```

Would this approach address your use case? Thanks!

**Comment by VarthanV** [comment]
Example code to do the comparision inside handler

```go
package main

import (
  "github.com/Varthan/idempotency"
  "github.com/gin-gonic/gin"
)

func main() {
  r := gin.Default()
  r.Use(idempotency.New(idempotency.Default()))

  r.POST("/transfer", func(c *gin.Context) {
    var existingIdempotentKey = "foo"
    // The value in the header will parsed and will be set in the context with the following key name by default 
    var idempotencyKeyFromCtx = c.GetString("IdempotencyKey")
    if idempotencyKeyFromCtx == existingIdempotentKey { 
        c.JSON(403, gin.H{"message":"send an new idempotency key"})
        return
    }
  })
  r.Run(":8000")
}

```

**Comment by sunnyyssh** [comment]
Thanks!
